@startuml

title __TOWER's Class Diagram__\n

  namespace de.dhbw {
    namespace map.objects.tower {
      abstract class de.dhbw.map.objects.tower.ATower {
          # damage : int
          # headImage : Optional<ImageView>
          - baseImage : ImageView
          - costs : int
          - fireRate : int
          - id : UUID
          - level : int
          - range : int
          - starlvlThree : ImageView
          - starlvlTwo : ImageView
          - task : TimerTask
          - x : int
          - y : int
          + ATower()
          + calculateDelay()
          + fire()
          + getBaseImage()
          + getCosts()
          {abstract} + getCosts()
          + getDamage()
          {abstract} + getDamage()
          + getDistance()
          + getField()
          + getFireRate()
          {abstract} + getFireRate()
          + getHeadImage()
          + getId()
          + getLevel()
          + getNearestEnemy()
          + getPosition()
          + getPositionX()
          + getPositionY()
          + getRange()
          {abstract} + getRange()
          + getStarlvlThree()
          + getStarlvlTwo()
          + getTask()
          + getTowerType()
          + isEnemyInRange()
          + rotateImage()
          + setBaseImage()
          + setHeadImage()
          + setTask()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.tower {
      class de.dhbw.map.objects.tower.TowerArtillery {
          - artilleryTowerImage : ImageView
          + TowerArtillery()
          + TowerArtillery()
          + fire()
          + getCosts()
          + getDamage()
          + getFireRate()
          + getRange()
          {static} + getTowerArtilleryCostsByLevel()
          {static} - getTowerArtilleryDamageByLevel()
          {static} - getTowerArtilleryFirerateByLevel()
          {static} - getTowerArtilleryRangeByLevel()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.tower {
      class de.dhbw.map.objects.tower.TowerBoombastic {
          + TowerBoombastic()
          + fire()
          + getCosts()
          + getDamage()
          + getFireRate()
          + getRange()
          {static} + getTowerBoombasticCostsByLevel()
          {static} - getTowerBoombasticDamageByLevel()
          {static} - getTowerBoombasticFirerateByLevel()
          {static} - getTowerBoombasticRangeByLevel()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.tower {
      class de.dhbw.map.objects.tower.TowerFreezer {
          - slowness : int
          + TowerFreezer()
          + TowerFreezer()
          + fire()
          + getCosts()
          + getDamage()
          + getFireRate()
          {static} + getFreezerCostsByLevel()
          + getRange()
          + getSlowness()
          {static} - getFreezerDamageByLevel()
          {static} - getFreezerFirerateByLevel()
          {static} - getFreezerRangeByLevel()
          {static} - getFreezerSlownessByLevel()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.tower {
      enum TowerType {
        ARTILLERY
        ASSAULTLASER
        BOOMBASTIC
        FREEZER
        PLASMARIZER
        drawable
        price
        type
      }
    }
  }
  

  de.dhbw.map.objects.tower.ATower -up-|> de.dhbw.game.ATimerUsage
  de.dhbw.map.objects.tower.ATower o-- de.dhbw.activities.GameActivity : gameActivity
  de.dhbw.map.objects.tower.ATower o-- de.dhbw.map.objects.enemy.Enemy : targetedEnemy
  de.dhbw.map.objects.tower.ATower o-- de.dhbw.map.structure.Field : field
  de.dhbw.map.objects.tower.ATower o-- de.dhbw.util.SortingUtil : sortingUtil
  de.dhbw.map.objects.tower.ATower o-- de.dhbw.map.objects.tower.TowerType : towerType
  de.dhbw.map.objects.tower.TowerArtillery -up-|> de.dhbw.map.objects.tower.ATower
  de.dhbw.map.objects.tower.TowerBoombastic -up-|> de.dhbw.map.objects.tower.ATower
  de.dhbw.map.objects.tower.TowerFreezer -up-|> de.dhbw.map.objects.tower.ATower


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
