@startuml

title __TOWER's Class Diagram__\n

  namespace de.dhbw {
    namespace map.objects.tower {
      class de.dhbw.map.objects.tower.Bullet {
          - bulletImage : ImageView
          - x : int
          - y : int
          + Bullet()
          + getPosition()
          + move()
          + moveTo()
          + visualizeShot()
          - getBulletRotation()
          - setMidpointOfPositions()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.tower {
      class de.dhbw.map.objects.tower.DefTower {
          - defTowerImage : ImageView
          + DefTower()
          + fire()
          {static} - getDefTowerCostsByLevel()
          {static} - getDefTowerDamageByLevel()
          {static} - getDefTowerFirerateByLevel()
          {static} - getDefTowerRangeByLevel()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.tower {
      abstract class de.dhbw.map.objects.tower.Tower {
          # damage : int
          - costs : int
          - fireRate : int
          - id : UUID
          - label : String
          - range : int
          - task : TimerTask
          - x : int
          - y : int
          + Tower()
          + fire()
          + getCosts()
          + getDamage()
          + getDistance()
          + getFireRate()
          + getId()
          + getLabel()
          + getNearestEnemy()
          + getPosition()
          + getPositionX()
          + getPositionY()
          + getRange()
          + getTask()
          + isEnemyInRange()
          + rotateImage()
          + setTask()
      }
    }
  }
  

  de.dhbw.map.objects.tower.Bullet o-- de.dhbw.util.Position : targetPos
  de.dhbw.map.objects.tower.Bullet o-- de.dhbw.map.objects.enemy.Enemy : targetedEnemy
  de.dhbw.map.objects.tower.Bullet o-- de.dhbw.map.objects.tower.DefTower : tower
  de.dhbw.map.objects.tower.DefTower -up-|> de.dhbw.map.objects.tower.Tower
  de.dhbw.map.objects.tower.Tower o-- de.dhbw.map.objects.enemy.Enemy : targetedEnemy
  de.dhbw.map.objects.tower.Tower o-- de.dhbw.util.SortingUtil : sortingUtil


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
