@startuml

title __UTIL's Class Diagram__\n

  namespace de.dhbw {
    namespace util {
      class de.dhbw.util.Constants {
          {static} + AMOUNT_COLUMNS : int
          {static} + AMOUNT_ROWS : int
          {static} + BULLET_SIZE_PARAMS : LayoutParams
          {static} + BULLET_SPEED : int
          {static} + DEF_TOWER_LEVEL_1_COSTS : int
          {static} + DEF_TOWER_LEVEL_1_DAMAGE : int
          {static} + DEF_TOWER_LEVEL_1_FIRERATE_IN_SECONDS : int
          {static} + DEF_TOWER_LEVEL_1_RANGE_IN_PIXELS : int
          {static} + DEF_TOWER_LEVEL_1_TOWER_SIZE_PARAMS : LayoutParams
          {static} + DRAWABLE_BULLET : int
          {static} + DRAWABLE_TANK : int
          {static} + DRAWABLE_TANK_HITTED : int
          {static} + DRAWABLE_TOWER : int
          {static} + FIELD_SIZE : int
          {static} + TANK_ENEMY_SIZE_PARAMS : LayoutParams
          {static} + TANK_LEVEL_1_HEALTHPOINTS : int
          {static} + TANK_LEVEL_1_SPEED : int
          {static} + TANK_LEVEL_2_HEALTHPOINTS : int
          {static} + TANK_LEVEL_2_SPEED : int
      }
    }
  }
  

  namespace de.dhbw {
    namespace util {
      enum Direction {
        DOWN
        LEFT
        RIGHT
        UP
      }
    }
  }
  

  namespace de.dhbw {
    namespace util {
      class de.dhbw.util.ObjectStorage {
          {static} - context : Context
          {static} - gameActivity : GameActivity
          {static} - mapLayout : FrameLayout
          {static} - mapStructure : MapStructure
          {static} - matchField : MatchField
          {static} + getContext()
          {static} + getGameActivity()
          {static} + getMapLayout()
          {static} + getMapStructure()
          {static} + getMatchField()
          {static} + setContext()
          {static} + setGameActivity()
          {static} + setMapLayout()
          {static} + setMapStructure()
          {static} + setMatchField()
      }
    }
  }
  

  namespace de.dhbw {
    namespace util {
      class de.dhbw.util.Position {
          - x : int
          - y : int
          + Position()
          + equals()
          + getX()
          + getY()
          + toString()
      }
    }
  }
  

  namespace de.dhbw {
    namespace util {
      class de.dhbw.util.SortingUtil {
          + SortingUtil()
          {static} + getSortedListBySortingMapByValue()
          + sortMapByValue()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
