@startuml

title __MATCH's Class Diagram__\n

  namespace de.dhbw {
    namespace game {
      namespace match {
        abstract class de.dhbw.game.match.AMatch {
            - count : int
            - extendable : boolean
            - startMoney : int
            - waveTime : int
            - waves : List<AWave>
            + calculateDelay()
            {abstract} + create()
            + getCurrent()
            + getCurrentWaveNumber()
            + getStartMoney()
            + getWaveTime()
            + hasNext()
            + next()
            ~ AMatch()
            ~ addWaves()
        }
      }
    }
  }
  

  namespace de.dhbw {
    namespace game {
      namespace match {
        class de.dhbw.game.match.EasyMatch {
            {static} - firstWaveTankL1 : WaveComposition
            {static} - firstWaveTankL2 : WaveComposition
            {static} - fithhWaveTankL3 : WaveComposition
            {static} - fourthWaveTankL2 : WaveComposition
            {static} - fourthWaveTankL3 : WaveComposition
            {static} - secondWaveTankL1 : WaveComposition
            {static} - secondWaveTankL2 : WaveComposition
            {static} - startMoney : int
            {static} - thirdWaveTankL2 : WaveComposition
            {static} - waveTime : int
            + EasyMatch()
            + create()
        }
      }
    }
  }
  

  namespace de.dhbw {
    namespace game {
      namespace match {
        class de.dhbw.game.match.HardMatch {
            {static} - firstWaveTankL1 : WaveComposition
            {static} - firstWaveTankL2 : WaveComposition
            {static} - secondWaveTankL1 : WaveComposition
            {static} - secondWaveTankL2 : WaveComposition
            {static} - thirdWaveTankL2 : WaveComposition
            {static} - waveTime : int
            + HardMatch()
            + create()
        }
      }
    }
  }
  

  namespace de.dhbw {
    namespace game {
      namespace match {
        class de.dhbw.game.match.MediumMatch {
            {static} - firstWaveTankL1 : WaveComposition
            {static} - firstWaveTankL2 : WaveComposition
            {static} - secondWaveTankL1 : WaveComposition
            {static} - secondWaveTankL2 : WaveComposition
            {static} - thirdWaveTankL2 : WaveComposition
            {static} - waveTime : int
            + MediumMatch()
            + create()
        }
      }
    }
  }
  

  de.dhbw.game.match.AMatch -up-|> de.dhbw.game.ATimerUsage
  de.dhbw.game.match.EasyMatch -up-|> de.dhbw.game.match.AMatch
  de.dhbw.game.match.HardMatch -up-|> de.dhbw.game.match.AMatch
  de.dhbw.game.match.MediumMatch -up-|> de.dhbw.game.match.AMatch


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
