@startuml

title __BULLET's Class Diagram__\n

  namespace de.dhbw {
    namespace map.objects.bullet {
      abstract class de.dhbw.map.objects.bullet.ABullet {
          # damage : int
          - bulletImage : ImageView
          - x : int
          - y : int
          + ABullet()
          + ABullet()
          # hitEnemy()
          - applyBulletOffset()
          - getBulletRotation()
          - setMidpointOfPositions()
          - startAnimation()
          - startLogicalShooting()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.bullet {
      class de.dhbw.map.objects.bullet.Bomb {
          - allEnemies : List<Enemy>
          - range : int
          + Bomb()
          + Bomb()
          + getEnemiesToHit()
          # hitEnemy()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.bullet {
      class de.dhbw.map.objects.bullet.Projectile {
          + Projectile()
          + Projectile()
          + Projectile()
      }
    }
  }
  

  namespace de.dhbw {
    namespace map.objects.bullet {
      class de.dhbw.map.objects.bullet.SnowFlake {
          - slowness : int
          + SnowFlake()
          + SnowFlake()
          # hitEnemy()
      }
    }
  }
  

  de.dhbw.map.objects.bullet.ABullet o-- de.dhbw.map.objects.enemy.AEnemy : targetEnemy
  de.dhbw.map.objects.bullet.ABullet o-- de.dhbw.activities.GameActivity : gameActivity
  de.dhbw.map.objects.bullet.ABullet o-- de.dhbw.util.Position : targetPos
  de.dhbw.map.objects.bullet.Bomb -up-|> de.dhbw.map.objects.bullet.ABullet
  de.dhbw.map.objects.bullet.Projectile -up-|> de.dhbw.map.objects.bullet.ABullet
  de.dhbw.map.objects.bullet.SnowFlake -up-|> de.dhbw.map.objects.bullet.ABullet


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
